
ALTER SESSION SET CURRENT_SCHEMA=&&1 ;
ALTER SESSION SET NLS_LENGTH_SEMANTICS=BYTE;


CREATE TABLE JPS_DN (
        ENTRYID                 NUMBER NOT NULL,
        RDN                     VARCHAR2(1024) NOT NULL,
        PARENTDN                VARCHAR2(1024)  NOT NULL,
        CONSTRAINT JPS_DN_PK PRIMARY KEY (ENTRYID) ENABLE) ;

CREATE TABLE JPS_ATTRS (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRNAME        VARCHAR2(256) NOT NULL,
        ATTRVAL         VARCHAR2(4000), 
        ATTRKIND	NUMBER,
        CONSTRAINT JPS_ATTRS_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE
        ) ;
        
CREATE TABLE JPS_ATTRS_BINARY (
        JPS_ATTRS_ID            NUMBER NOT NULL,
        JPS_DN_ENTRYID          NUMBER NOT NULL,
        ATTRNAME                VARCHAR2(256) NOT NULL,
        ATTRVAL                 BLOB,
        CONSTRAINT JPS_ATTRS_BINARY_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT ATTR_DN_FK_BINARY FOREIGN KEY(JPS_DN_ENTRYID) REFERENCES JPS_DN(ENTRYID) ON DELETE CASCADE,
        CONSTRAINT ATTR_ID_FK_BINARY FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
) ;
        
CREATE TABLE SEQUENCE 
   (
     SEQ_NAME                VARCHAR2(20) NOT NULL, 
     SEQ_COUNT               NUMBER NOT NULL, 
     CONSTRAINT SEQUENCE_PK PRIMARY KEY (SEQ_NAME) ENABLE
   ) ;

create table JPS_CHANGELOG
(
  LOGID         NUMBER not null,
  VERSION       NUMBER not null,
  APPLICATIONDN VARCHAR2(1024) not null,
  ACTION        VARCHAR2(1024) not null,
  DN            VARCHAR2(1024) not null,
  ATTRNAME      VARCHAR2(1024),
  ATTRVALUE     VARCHAR2(4000),
  ENTITYTYPE    VARCHAR2(1024),
  ENTITYNAME    VARCHAR2(1024),
  POLICYDOMAINNAME VARCHAR2(1024),
  TID           VARCHAR2(1024),
  CHANGELOGTYPE VARCHAR2(1024),
  CREATEDATE    TIMESTAMP default CURRENT_TIMESTAMP,
  constraint CHANGELOG_PK primary key (LOGID) ENABLE
); 

create table  JPS_ENTITY_LOCK
(
  ENTITY_KEY VARCHAR2(1024) not null,
  constraint ENTITY_LOCK_PK primary key (ENTITY_KEY) enable
);

CREATE INDEX IDX_JPS_PARENTDN_ID ON JPS_DN (PARENTDN, ENTRYID);
CREATE UNIQUE INDEX IDX_JPS_RDN_PDN ON JPS_DN (RDN, PARENTDN);
CREATE INDEX IDX_JPS_CONCAT_DN ON JPS_DN (CONCAT(PARENTDN, RDN));
CREATE INDEX IDX_ATTR_DNID ON JPS_ATTRS (JPS_DN_ENTRYID);
CREATE INDEX IDX_ATTR_NAME ON JPS_ATTRS (ATTRNAME);
CREATE INDEX JPS_ATTRS_KIND ON JPS_ATTRS (ATTRKIND);

CREATE INDEX IDX_ATTR_DNID_BINARY ON JPS_ATTRS_BINARY (JPS_DN_ENTRYID);
CREATE INDEX IDX_ATTR_NAME_BINARY ON JPS_ATTRS_BINARY (ATTRNAME);

CREATE INDEX IDX_LOG_APPACTIONTIME ON JPS_CHANGELOG(APPLICATIONDN, ACTION, CREATEDATE);
CREATE INDEX IDX_LOG_DN ON JPS_CHANGELOG(DN);
CREATE INDEX IDX_LOG_DNACTIONTIME ON JPS_CHANGELOG(DN, ACTION, CREATEDATE);
CREATE INDEX IDX_LOG_CREATEDATE ON JPS_CHANGELOG(CREATEDATE);
CREATE INDEX IDX_LOG_ENTITYTYPE ON JPS_CHANGELOG(ENTITYTYPE);
CREATE INDEX IDX_LOG_APPDN_VERSION_TYPE on JPS_CHANGELOG (APPLICATIONDN, VERSION, CHANGELOGTYPE);

CREATE TABLE JPS_ENTRYID_DELETED (
       ENTRYID NUMBER NOT NULL,
       CONSTRAINT JPS_ENTRYID_DELETED_PK PRIMARY KEY ( ENTRYID ) ENABLE
);

CREATE TABLE CT_0 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_0_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_0_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_0_DNID ON CT_0 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_0_ATTRVAL ON CT_0 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_1 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_1_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_1_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_1_DNID ON CT_1 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_1_ATTRVAL ON CT_1 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_2 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_2_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_2_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_2_DNID ON CT_2 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_2_ATTRVAL ON CT_2 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_3 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_3_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_3_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_3_DNID ON CT_3 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_3_ATTRVAL ON CT_3 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_4 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_4_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_4_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_4_DNID ON CT_4 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_4_ATTRVAL ON CT_4 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_5 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        SUBTYPENAME     VARCHAR2(256),        
        CONSTRAINT CT_5_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_5_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_5_DNID ON CT_5 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_5_ATTRVAL ON CT_5 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_6 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_6_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_6_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_6_DNID ON CT_6 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_6_ATTRVAL ON CT_6 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_6_1 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(3000),
        CONSTRAINT CT_6_1_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_6_1_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_6_1_DNID ON CT_6_1 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_6_1_ATTRVAL ON CT_6_1 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_6_2 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(3000),
        CONSTRAINT CT_6_2_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_6_2_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_6_2_DNID ON CT_6_2 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_6_2_ATTRVAL ON CT_6_2 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_6_3 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(3000),
        CONSTRAINT CT_6_3_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_6_3_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_6_3_DNID ON CT_6_3 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_6_3_ATTRVAL ON CT_6_3 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_6_4 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(3000),
        CONSTRAINT CT_6_4_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_6_4_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_6_4_DNID ON CT_6_4 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_6_4_ATTRVAL ON CT_6_4 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_7 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_7_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_7_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_7_DNID ON CT_7 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_7_ATTRVAL ON CT_7 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_8 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_8_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_8_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_8_DNID ON CT_8 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_8_ATTRVAL ON CT_8 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_9 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
	SUBTYPENAME     VARCHAR2(256),
        CONSTRAINT CT_9_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_9_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_9_DNID ON CT_9 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_9_ATTRVAL ON CT_9 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_9_1 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(3000),
        CONSTRAINT CT_9_1_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_9_1_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_9_1_DNID ON CT_9_1 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_9_1_ATTRVAL ON CT_9_1 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_9_2 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(3000),
        CONSTRAINT CT_9_2_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_9_2_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_9_2_DNID ON CT_9_2 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_9_2_ATTRVAL ON CT_9_2 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_9_3 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(3000),
        CONSTRAINT CT_9_3_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_9_3_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_9_3_DNID ON CT_9_3 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_9_3_ATTRVAL ON CT_9_3 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_10 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_10_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_10_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_10_DNID ON CT_10 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_10_ATTRVAL ON CT_10 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_11 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_11_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_11_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_11_DNID ON CT_11 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_11_ATTRVAL ON CT_11 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_12 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_12_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_12_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_12_DNID ON CT_12 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_12_ATTRVAL ON CT_12 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_13 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_13_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_13_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_13_DNID ON CT_13 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_13_ATTRVAL ON CT_13 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_14 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_14_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_14_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_14_DNID ON CT_14 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_14_ATTRVAL ON CT_14 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_15 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_15_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_15_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_15_DNID ON CT_15 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_15_ATTRVAL ON CT_15 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_16 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_16_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_16_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_16_DNID ON CT_16 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_16_ATTRVAL ON CT_16 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_17 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_17_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_17_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_17_DNID ON CT_17 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_17_ATTRVAL ON CT_17 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_18 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_18_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_18_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_18_DNID ON CT_18 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_18_ATTRVAL ON CT_18 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_19 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_19_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_19_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_19_DNID ON CT_19 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_19_ATTRVAL ON CT_19 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_20 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_20_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_20_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_20_DNID ON CT_20 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_20_ATTRVAL ON CT_20 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_21 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_21_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_21_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_21_DNID ON CT_21 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_21_ATTRVAL ON CT_21 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_22 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        SUBTYPENAME     VARCHAR2(256),        
        CONSTRAINT CT_22_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_22_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_22_DNID ON CT_22 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_22_ATTRVAL ON CT_22 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_23 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_23_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_23_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_23_DNID ON CT_23 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_23_ATTRVAL ON CT_23 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_24 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        SUBTYPENAME     VARCHAR2(256),        
        CONSTRAINT CT_24_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_24_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_24_DNID ON CT_24 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_24_ATTRVAL ON CT_24 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_25 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_25_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_25_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_25_DNID ON CT_25 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_25_ATTRVAL ON CT_25 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_26 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        SUBTYPENAME     VARCHAR2(256),        
        CONSTRAINT CT_26_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_26_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_26_DNID ON CT_26 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_26_ATTRVAL ON CT_26 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_27 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_27_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_27_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_27_DNID ON CT_27 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_27_ATTRVAL ON CT_27 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_28 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_28_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_28_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_28_DNID ON CT_28 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_28_ATTRVAL ON CT_28 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_29 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_29_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_29_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_29_DNID ON CT_29 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_29_ATTRVAL ON CT_29 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_30 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_30_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_30_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_30_DNID ON CT_30 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_30_ATTRVAL ON CT_30 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_31 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_31_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_31_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_31_DNID ON CT_31 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_31_ATTRVAL ON CT_31 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_32 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_32_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_32_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_32_DNID ON CT_32 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_32_ATTRVAL ON CT_32 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_33 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_33_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_33_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_33_DNID ON CT_33 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_33_ATTRVAL ON CT_33 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_34 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_34_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_34_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_34_DNID ON CT_34 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_34_ATTRVAL ON CT_34 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_35 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        SUBTYPENAME     VARCHAR2(256),       
        CONSTRAINT CT_35_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_35_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_35_DNID ON CT_35 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_35_ATTRVAL ON CT_35 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_36 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_36_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_36_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_36_DNID ON CT_36 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_36_ATTRVAL ON CT_36 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_37 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_37_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_37_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_37_DNID ON CT_37 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_37_ATTRVAL ON CT_37 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_38 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_38_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_38_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_38_DNID ON CT_38 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_38_ATTRVAL ON CT_38 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_39 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_39_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_39_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_39_DNID ON CT_39 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_39_ATTRVAL ON CT_39 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_40 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_40_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_40_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_40_DNID ON CT_40 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_40_ATTRVAL ON CT_40 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_41 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_41_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_41_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_41_DNID ON CT_41 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_41_ATTRVAL ON CT_41 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_42 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_42_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_42_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_42_DNID ON CT_42 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_42_ATTRVAL ON CT_42 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_43 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_43_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_43_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_43_DNID ON CT_43 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_43_ATTRVAL ON CT_43 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_44 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_44_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_44_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_44_DNID ON CT_44 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_44_ATTRVAL ON CT_44 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_45 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_45_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_45_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_45_DNID ON CT_45 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_45_ATTRVAL ON CT_45 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_46 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_46_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_46_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_46_DNID ON CT_46 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_46_ATTRVAL ON CT_46 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_47 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_47_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_47_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_47_DNID ON CT_47 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_47_ATTRVAL ON CT_47 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_48 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_48_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_48_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_48_DNID ON CT_48 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_48_ATTRVAL ON CT_48 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_49 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_49_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_49_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_49_DNID ON CT_49 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_49_ATTRVAL ON CT_49 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_50 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_50_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_50_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_50_DNID ON CT_50 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_50_ATTRVAL ON CT_50 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_51 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_51_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_51_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_51_DNID ON CT_51 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_51_ATTRVAL ON CT_51 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_52 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_52_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_52_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_52_DNID ON CT_52 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_52_ATTRVAL ON CT_52 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_53 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_53_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_53_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_53_DNID ON CT_53 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_53_ATTRVAL ON CT_53 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_54 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_54_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_54_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_54_DNID ON CT_54 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_54_ATTRVAL ON CT_54 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_55 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_55_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_55_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_55_DNID ON CT_55 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_55_ATTRVAL ON CT_55 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_56 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_56_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_56_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_56_DNID ON CT_56 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_56_ATTRVAL ON CT_56 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_57 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_57_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_57_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_57_DNID ON CT_57 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_57_ATTRVAL ON CT_57 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_58 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_58_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_58_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_58_DNID ON CT_58 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_58_ATTRVAL ON CT_58 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_59 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_59_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_59_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_59_DNID ON CT_59 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_59_ATTRVAL ON CT_59 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_60 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_60_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_60_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_60_DNID ON CT_60 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_60_ATTRVAL ON CT_60 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_61 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_61_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_61_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_61_DNID ON CT_61 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_61_ATTRVAL ON CT_61 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_62 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_62_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_62_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_62_DNID ON CT_62 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_62_ATTRVAL ON CT_62 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_63 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_63_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_63_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_63_DNID ON CT_63 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_63_ATTRVAL ON CT_63 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_64 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_64_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_64_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_64_DNID ON CT_64 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_64_ATTRVAL ON CT_64 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_65 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_65_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_65_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_65_DNID ON CT_65 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_65_ATTRVAL ON CT_65 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_66 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_66_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_66_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_66_DNID ON CT_66 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_66_ATTRVAL ON CT_66 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_67 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_67_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_67_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_67_DNID ON CT_67 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_67_ATTRVAL ON CT_67 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_68 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_68_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_68_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_68_DNID ON CT_68 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_68_ATTRVAL ON CT_68 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_69 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_69_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_69_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_69_DNID ON CT_69 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_69_ATTRVAL ON CT_69 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_70 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_70_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_70_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_70_DNID ON CT_70 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_70_ATTRVAL ON CT_70 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_71 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_71_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_71_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_71_DNID ON CT_71 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_71_ATTRVAL ON CT_71 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_72 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_72_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_72_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_72_DNID ON CT_72 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_72_ATTRVAL ON CT_72 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_73 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_73_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_73_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_73_DNID ON CT_73 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_73_ATTRVAL ON CT_73 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_74 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_74_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_74_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_74_DNID ON CT_74 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_74_ATTRVAL ON CT_74 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_75 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_75_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_75_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_75_DNID ON CT_75 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_75_ATTRVAL ON CT_75 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_76 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_76_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_76_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_76_DNID ON CT_76 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_76_ATTRVAL ON CT_76 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_77 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_77_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_77_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_77_DNID ON CT_77 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_77_ATTRVAL ON CT_77 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_78 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_78_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_78_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_78_DNID ON CT_78 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_78_ATTRVAL ON CT_78 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_79 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_79_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_79_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_79_DNID ON CT_79 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_79_ATTRVAL ON CT_79 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_80 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_80_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_80_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_80_DNID ON CT_80 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_80_ATTRVAL ON CT_80 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_81 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_81_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_81_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_81_DNID ON CT_81 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_81_ATTRVAL ON CT_81 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_82 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_82_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_82_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_82_DNID ON CT_82 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_82_ATTRVAL ON CT_82 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_83 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_83_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_83_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_83_DNID ON CT_83 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_83_ATTRVAL ON CT_83 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_84 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_84_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_84_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_84_DNID ON CT_84 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_84_ATTRVAL ON CT_84 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_85 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_85_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_85_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_85_DNID ON CT_85 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_85_ATTRVAL ON CT_85 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_86 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_86_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_86_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_86_DNID ON CT_86 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_86_ATTRVAL ON CT_86 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_87 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_87_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_87_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_87_DNID ON CT_87 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_87_ATTRVAL ON CT_87 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_88 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_88_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_88_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_88_DNID ON CT_88 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_88_ATTRVAL ON CT_88 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_89 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_89_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_89_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_89_DNID ON CT_89 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_89_ATTRVAL ON CT_89 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_90 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_90_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_90_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_90_DNID ON CT_90 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_90_ATTRVAL ON CT_90 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_91 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_91_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_91_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_91_DNID ON CT_91 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_91_ATTRVAL ON CT_91 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_92 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_92_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_92_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_92_DNID ON CT_92 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_92_ATTRVAL ON CT_92 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_93 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_93_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_93_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_93_DNID ON CT_93 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_93_ATTRVAL ON CT_93 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_94 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_94_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_94_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_94_DNID ON CT_94 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_94_ATTRVAL ON CT_94 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_95 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_95_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_95_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_95_DNID ON CT_95 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_95_ATTRVAL ON CT_95 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_96 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_96_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_96_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_96_DNID ON CT_96 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_96_ATTRVAL ON CT_96 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_97 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_97_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_97_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_97_DNID ON CT_97 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_97_ATTRVAL ON CT_97 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_98 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_98_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_98_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_98_DNID ON CT_98 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_98_ATTRVAL ON CT_98 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_99 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_99_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_99_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_99_DNID ON CT_99 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_99_ATTRVAL ON CT_99 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_100 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_100_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_100_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_100_DNID ON CT_100 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_100_ATTRVAL ON CT_100 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_101 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_101_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_101_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_101_DNID ON CT_101 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_101_ATTRVAL ON CT_101 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_102 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_102_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_102_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_102_DNID ON CT_102 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_102_ATTRVAL ON CT_102 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_103 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_103_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_103_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_103_DNID ON CT_103 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_103_ATTRVAL ON CT_103 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_104 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_104_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_104_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_104_DNID ON CT_104 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_104_ATTRVAL ON CT_104 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_105 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_105_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_105_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_105_DNID ON CT_105 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_105_ATTRVAL ON CT_105 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_106 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_106_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_106_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_106_DNID ON CT_106 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_106_ATTRVAL ON CT_106 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_107 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_107_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_107_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_107_DNID ON CT_107 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_107_ATTRVAL ON CT_107 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_108 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_108_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_108_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_108_DNID ON CT_108 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_108_ATTRVAL ON CT_108 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_109 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_109_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_109_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_109_DNID ON CT_109 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_109_ATTRVAL ON CT_109 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_110 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_110_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_110_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_110_DNID ON CT_110 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_110_ATTRVAL ON CT_110 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_111 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_111_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_111_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_111_DNID ON CT_111 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_111_ATTRVAL ON CT_111 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_112 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_112_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_112_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_112_DNID ON CT_112 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_112_ATTRVAL ON CT_112 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_113 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_113_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_113_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_113_DNID ON CT_113 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_113_ATTRVAL ON CT_113 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_114 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_114_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_114_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_114_DNID ON CT_114 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_114_ATTRVAL ON CT_114 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_115 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_115_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_115_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_115_DNID ON CT_115 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_115_ATTRVAL ON CT_115 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_116 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_116_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_116_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_116_DNID ON CT_116 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_116_ATTRVAL ON CT_116 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_117 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_117_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_117_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_117_DNID ON CT_117 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_117_ATTRVAL ON CT_117 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_118 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_118_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_118_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_118_DNID ON CT_118 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_118_ATTRVAL ON CT_118 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_119 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_119_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_119_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_119_DNID ON CT_119 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_119_ATTRVAL ON CT_119 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_120 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_120_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_120_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_120_DNID ON CT_120 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_120_ATTRVAL ON CT_120 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_121 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_121_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_121_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_121_DNID ON CT_121 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_121_ATTRVAL ON CT_121 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_122 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_122_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_122_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_122_DNID ON CT_122 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_122_ATTRVAL ON CT_122 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_123 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_123_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_123_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_123_DNID ON CT_123 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_123_ATTRVAL ON CT_123 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_124 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_124_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_124_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_124_DNID ON CT_124 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_124_ATTRVAL ON CT_124 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_125 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_125_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_125_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_125_DNID ON CT_125 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_125_ATTRVAL ON CT_125 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_126 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_126_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_126_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_126_DNID ON CT_126 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_126_ATTRVAL ON CT_126 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_127 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_127_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_127_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_127_DNID ON CT_127 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_127_ATTRVAL ON CT_127 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_128 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_128_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_128_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_128_DNID ON CT_128 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_128_ATTRVAL ON CT_128 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_129 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_129_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_129_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_129_DNID ON CT_129 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_129_ATTRVAL ON CT_129 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_130 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_130_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_130_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_130_DNID ON CT_130 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_130_ATTRVAL ON CT_130 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_131 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_131_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_131_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_131_DNID ON CT_131 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_131_ATTRVAL ON CT_131 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_132 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_132_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_132_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_132_DNID ON CT_132 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_132_ATTRVAL ON CT_132 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_133 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_133_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_133_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_133_DNID ON CT_133 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_133_ATTRVAL ON CT_133 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_134 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_134_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_134_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_134_DNID ON CT_134 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_134_ATTRVAL ON CT_134 (ATTRVAL, JPS_DN_ENTRYID);
CREATE TABLE CT_135 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_135_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_135_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_135_DNID ON CT_135 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_135_ATTRVAL ON CT_135 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_136 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_136_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_136_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_136_DNID ON CT_136 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_136_ATTRVAL ON CT_136 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_137 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_137_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_137_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_137_DNID ON CT_137 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_137_ATTRVAL ON CT_137 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_138 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_138_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_138_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_138_DNID ON CT_138 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_138_ATTRVAL ON CT_138 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_139 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),        
        CONSTRAINT CT_139_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_139_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_139_DNID ON CT_139 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_139_ATTRVAL ON CT_139 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_140 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),        
        CONSTRAINT CT_140_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_140_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_140_DNID ON CT_140 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_140_ATTRVAL ON CT_140 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_141 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),        
        CONSTRAINT CT_141_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_141_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_141_DNID ON CT_141 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_141_ATTRVAL ON CT_141 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_142 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),        
        CONSTRAINT CT_142_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_142_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_142_DNID ON CT_142 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_142_ATTRVAL ON CT_142 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_143 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),        
        CONSTRAINT CT_143_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_143_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_143_DNID ON CT_143 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_143_ATTRVAL ON CT_143 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_144 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        SUBTYPENAME     VARCHAR2(256),        
        CONSTRAINT CT_144_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_144_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_144_DNID ON CT_144 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_144_ATTRVAL ON CT_144 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_145 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),        
        CONSTRAINT CT_145_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_145_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_145_DNID ON CT_145 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_145_ATTRVAL ON CT_145 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_146 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),        
        CONSTRAINT CT_146_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_146_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_146_DNID ON CT_146 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_146_ATTRVAL ON CT_146 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_147 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        SUBTYPENAME     VARCHAR2(256),        
        CONSTRAINT CT_147_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_147_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_147_DNID ON CT_147 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_147_ATTRVAL ON CT_147 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_148 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_148_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_148_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_148_DNID ON CT_148 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_148_ATTRVAL ON CT_148 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_149 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_149_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_149_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_149_DNID ON CT_149 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_149_ATTRVAL ON CT_149 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_150 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_150_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_150_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_150_DNID ON CT_150 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_150_ATTRVAL ON CT_150 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_151 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_151_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_151_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_151_DNID ON CT_151 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_151_ATTRVAL ON CT_151 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_152 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_152_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_152_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_152_DNID ON CT_152 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_152_ATTRVAL ON CT_152 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_153 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_153_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_153_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_153_DNID ON CT_153 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_153_ATTRVAL ON CT_153 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_154 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_154_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_154_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_154_DNID ON CT_154 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_154_ATTRVAL ON CT_154 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_155 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_155_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_155_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_155_DNID ON CT_155 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_155_ATTRVAL ON CT_155 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_156 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_156_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_156_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_156_DNID ON CT_156 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_156_ATTRVAL ON CT_156 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_157 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_157_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_157_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_157_DNID ON CT_157 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_157_ATTRVAL ON CT_157 (ATTRVAL, JPS_DN_ENTRYID);

CREATE SEQUENCE SEQ_STMT
  INCREMENT BY 1
  START WITH 1
  NOCACHE
  NOCYCLE;


CREATE TABLE OES_SQL_STMTS (
    SEQ_NUM           NUMBER NOT NULL,
    TARGET_RAS_DB_NAME       VARCHAR2(4000) NOT NULL,
    SCHEMA            VARCHAR2(128),
    APP_NAME          VARCHAR2(4000) NOT NULL,
    VERSION           NUMBER NOT NULL,
    ENTITY_TYPE       VARCHAR2(128) NOT NULL,
    ENTITY_NAME       VARCHAR2(4000) NOT NULL,
    CATEGORY          VARCHAR2(128) NOT NULL,
    DN                VARCHAR2(4000) NOT NULL,
    ACTION_TYPE       VARCHAR2(128) NOT NULL,
    STMT              VARCHAR2(4000) NOT NULL,
    DISTRIBUTION_TIME TIMESTAMP NOT NULL,
    STATE             VARCHAR2(1) NOT NULL,
    EXCEPTION         VARCHAR2(4000)
);
CREATE INDEX IDX_OES_SQL_STMTS_SEQNUM ON OES_SQL_STMTS (SEQ_NUM);
CREATE INDEX IDX_OES_SQL_STMTS_DBNAME ON OES_SQL_STMTS (STATE, TARGET_RAS_DB_NAME);


CREATE TABLE OES_DIST_ID_REF (
    DIST_ID           VARCHAR2(128) NOT NULL,
    REF_DIST_ID       VARCHAR2(128) NOT NULL,
    APP_NAME          VARCHAR2(4000) NOT NULL,
    VERSION           NUMBER NOT NULL,
    DISTRIBUTION_TIME TIMESTAMP NOT NULL
);

CREATE INDEX IDX_OES_DIST_ID_REF_AV ON OES_DIST_ID_REF (APP_NAME, VERSION);
CREATE INDEX IDX_OES_DIST_ID_REF_DA ON OES_DIST_ID_REF (DIST_ID, APP_NAME);

INSERT into SEQUENCE values('JPSDN_SEQ',5000);
INSERT into SEQUENCE values('JPSATTRS_SEQ',5000);
INSERT into SEQUENCE values('JPSCHANGELOG_SEQ',1000);

create sequence JPSDN_SEQ start with 5001  increment by 1 nocycle;
create sequence JPSATTRS_SEQ start with 5001 increment by 1000  nocycle nocache;
create sequence JPSCHANGELOG_SEQ start with 1001 increment by 1  nocycle;

